//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_History
    {
        public int ID { get; set; }
        public string logName { get; set; }
        public string logDescription { get; set; }
        public string logType { get; set; }
        public string logUser { get; set; }
        public System.DateTime logDate { get; set; }
    }
}
