//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_DebitorBillingPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_DebitorBillingPeriod()
        {
            this.key_DebitorBilling = new HashSet<key_DebitorBilling>();
            this.tran_DebitorRec = new HashSet<tran_DebitorRec>();
        }
    
        public int ID { get; set; }
        public string DebitorPeriodCode { get; set; }
        public System.DateTime DebitorDateFrom { get; set; }
        public System.DateTime DebitorDateTo { get; set; }
        public int DebitorBillingStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<key_DebitorBilling> key_DebitorBilling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_DebitorRec> tran_DebitorRec { get; set; }
    }
}
