//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_JobCreditor
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public int CreditorID { get; set; }
        public int ProductID { get; set; }
        public decimal ProductSellPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SourceFrom { get; set; }
    
        public virtual mas_Job mas_Job { get; set; }
        public virtual mas_Product mas_Product { get; set; }
        public virtual mas_Creditor mas_Creditor { get; set; }
    }
}
