//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_Creditor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tran_Creditor()
        {
            this.tran_DebitorRecDetail = new HashSet<tran_DebitorRecDetail>();
            this.tran_CreditorService = new HashSet<tran_CreditorService>();
        }
    
        public int ID { get; set; }
        public string TransactionCreditorCode { get; set; }
        public int BillingPeriodID { get; set; }
        public System.DateTime BillingDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionSeq { get; set; }
        public string DocumentNo { get; set; }
        public int TranUnitQuantity { get; set; }
        public bool IsOutsidePeriod { get; set; }
        public int CreditorID { get; set; }
        public int JobID { get; set; }
        public int ProductID { get; set; }
        public string CarLicense { get; set; }
        public string Driver { get; set; }
        public decimal TranWeight { get; set; }
        public decimal TranBuyPrice { get; set; }
        public decimal TranDiscount { get; set; }
        public bool IsVat { get; set; }
        public decimal TranVat { get; set; }
        public decimal TotalBeforeDiscount { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsPaid { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsCancel { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsUsed { get; set; }
        public string TranUnit { get; set; }
    
        public virtual mas_Product mas_Product { get; set; }
        public virtual tran_BillingPeriod tran_BillingPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_DebitorRecDetail> tran_DebitorRecDetail { get; set; }
        public virtual mas_Job mas_Job { get; set; }
        public virtual mas_Creditor mas_Creditor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorService> tran_CreditorService { get; set; }
    }
}
