//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_BillingPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tran_BillingPeriod()
        {
            this.key_DebitorBilling = new HashSet<key_DebitorBilling>();
            this.tran_Creditor = new HashSet<tran_Creditor>();
            this.tran_CreditorPrePaid = new HashSet<tran_CreditorPrePaid>();
        }
    
        public int ID { get; set; }
        public string BillingPeriodCode { get; set; }
        public System.DateTime BillingDateFrom { get; set; }
        public System.DateTime BillingDateTo { get; set; }
        public int BillingStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<key_DebitorBilling> key_DebitorBilling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_Creditor> tran_Creditor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorPrePaid> tran_CreditorPrePaid { get; set; }
    }
}
