//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrpt_TransactionCreditor
    {
        public int ID { get; set; }
        public string TransactionCreditorCode { get; set; }
        public int BillingPeriodID { get; set; }
        public string BillingPeriodCode { get; set; }
        public System.DateTime BillingDateFrom { get; set; }
        public System.DateTime BillingDateTo { get; set; }
        public int BillingStatus { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionSeq { get; set; }
        public string DocumentNo { get; set; }
        public bool IsOutsidePeriod { get; set; }
        public int CreditorID { get; set; }
        public string CreditorCode { get; set; }
        public string CreditorName { get; set; }
        public string CreditorAddress { get; set; }
        public string CreditorTel { get; set; }
        public string CreditorContact { get; set; }
        public int JobID { get; set; }
        public string JobCode { get; set; }
        public System.DateTime JobDateStart { get; set; }
        public string JobName { get; set; }
        public int DebtorID { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorName { get; set; }
        public string DebtorAddress { get; set; }
        public string DebtorTel { get; set; }
        public string DebtorContact { get; set; }
        public decimal Budget { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductPrice { get; set; }
        public string Reference { get; set; }
        public string CarLicense { get; set; }
        public string Driver { get; set; }
        public decimal TranWeight { get; set; }
        public decimal TranBuyPrice { get; set; }
        public decimal TranDiscount { get; set; }
        public bool IsVat { get; set; }
        public decimal TranVat { get; set; }
        public decimal TotalBeforeDiscount { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsPaid { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsCancel { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime BillingDate { get; set; }
        public int TranUnitQuantity { get; set; }
        public decimal PrepaidTotalAmount { get; set; }
        public string REM { get; set; }
        public string TranUnit { get; set; }
        public string TranDetail { get; set; }
        public string TranDetailAmt { get; set; }
    }
}
