//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrpt_VersusBuySell
    {
        public int ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string JobCode { get; set; }
        public string JobName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Reference { get; set; }
        public decimal TranBuyPrice { get; set; }
        public string TranUnit { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorName { get; set; }
        public string DebtorAddress { get; set; }
        public string DebtorTel { get; set; }
        public int JobID { get; set; }
        public decimal TranSellPrice { get; set; }
        public string DocumentNo { get; set; }
        public System.DateTime SellDate { get; set; }
        public string CreditorCode { get; set; }
        public string CreditorName { get; set; }
    }
}
