//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrpt_TransactionMill
    {
        public Nullable<int> CreditorServiceID { get; set; }
        public string CreditorServiceCode { get; set; }
        public string CreditorServiceName { get; set; }
        public Nullable<bool> IsVatD { get; set; }
        public Nullable<decimal> VatInt { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> TotalAmountD { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TranCreditorID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int DebitorPeriodID { get; set; }
        public string DebitorPeriodCode { get; set; }
        public System.DateTime DebitorDateFrom { get; set; }
        public System.DateTime DebitorDateTo { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorName { get; set; }
        public System.DateTime TransactionDateCr { get; set; }
        public int TransactionSeqCr { get; set; }
        public string DocumentNoCr { get; set; }
        public decimal TranWeight { get; set; }
        public string TransactionDebitorCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> IsVat { get; set; }
        public decimal TranVat { get; set; }
        public decimal TranDiscount { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalAmountByBill { get; set; }
        public decimal TranSellPrice { get; set; }
        public string JobCode { get; set; }
        public string CreditorCode { get; set; }
        public string CreditorName { get; set; }
        public int JobID { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductUnit { get; set; }
        public decimal TranDiscountCr { get; set; }
        public bool IsVatCr { get; set; }
        public decimal TranVatCr { get; set; }
        public decimal TotalBeforeDiscountCr { get; set; }
        public decimal TotalBeforeVatCr { get; set; }
        public decimal TotalAmountCr { get; set; }
        public string TranUnit { get; set; }
        public string JobName { get; set; }
        public int CreditorID { get; set; }
        public decimal TranBuyPrice { get; set; }
        public Nullable<bool> IsAtVat { get; set; }
        public Nullable<decimal> AtVatInt { get; set; }
        public Nullable<decimal> AtVatAmount { get; set; }
        public Nullable<int> ProductServiceID { get; set; }
        public Nullable<decimal> ProductServicePrice { get; set; }
        public string ProductServiceName { get; set; }
        public Nullable<System.DateTime> JobDateStart { get; set; }
    }
}
