//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrpt_TransactionDebitor_new
    {
        public long Inx { get; set; }
        public int MasterID { get; set; }
        public string TransactionDebitorCode { get; set; }
        public int DebitorPeriodID { get; set; }
        public string DebitorPeriodCode { get; set; }
        public System.DateTime DebitorDateFrom { get; set; }
        public System.DateTime DebitorDateTo { get; set; }
        public int DebitorBillingStatus { get; set; }
        public int DetailID { get; set; }
        public int DebitorID { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorName { get; set; }
        public string DebtorAddress { get; set; }
        public string DebtorTel { get; set; }
        public string DebtorContact { get; set; }
        public string DebtorTaxID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public bool IsReceived { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsCancel { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsVat { get; set; }
        public decimal TranVat { get; set; }
        public decimal TranDiscount { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalAmountByBill { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int TransactionCreditorID { get; set; }
        public decimal TranSellPrice { get; set; }
        public decimal TotalAmontDetail { get; set; }
        public string TransactionCreditorCode { get; set; }
        public int BillingPeriodID { get; set; }
        public string BillingPeriodCode { get; set; }
        public System.DateTime BillingDateFrom { get; set; }
        public System.DateTime BillingDateTo { get; set; }
        public int BillingStatus { get; set; }
        public System.DateTime BillingDateCr { get; set; }
        public System.DateTime TransactionDateCr { get; set; }
        public int TransactionSeqCr { get; set; }
        public string DocumentNoCr { get; set; }
        public int TranUnitQuantityCr { get; set; }
        public bool IsOutsidePeriodCr { get; set; }
        public int CreditorID { get; set; }
        public string CreditorCode { get; set; }
        public string CreditorName { get; set; }
        public string CreditorAddress { get; set; }
        public string CreditorTel { get; set; }
        public string CreditorContact { get; set; }
        public string CreditorTaxID { get; set; }
        public int JobID { get; set; }
        public string JobCode { get; set; }
        public System.DateTime JobDateStart { get; set; }
        public string JobName { get; set; }
        public decimal Budget { get; set; }
        public int DebtorID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Reference { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductUnit { get; set; }
        public string CarLicense { get; set; }
        public string Driver { get; set; }
        public decimal TranWeight { get; set; }
        public decimal TranBuyPrice { get; set; }
        public decimal TranDiscountCr { get; set; }
        public bool IsVatCr { get; set; }
        public decimal TranVatCr { get; set; }
        public decimal TotalBeforeDiscountCr { get; set; }
        public decimal TotalBeforeVatCr { get; set; }
        public decimal TotalAmountCr { get; set; }
        public bool IsPaid { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsUsed { get; set; }
        public string DocNo { get; set; }
        public string TranUnit { get; set; }
        public int TranCRID { get; set; }
    }
}
