//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sec_EmployeeUser
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsSecurity { get; set; }
        public bool IsSystemSetup { get; set; }
        public bool IsTransaction { get; set; }
        public bool IsReport { get; set; }
        public bool IsAdmin { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool NeedToApprove { get; set; }
        public string NeedToApproveBy { get; set; }
    }
}
