//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_DebitorRecDetail
    {
        public int ID { get; set; }
        public int MasterID { get; set; }
        public int TransactionCreditorID { get; set; }
        public decimal TranSellPrice { get; set; }
        public decimal TotalAmount { get; set; }
        public string DocNo { get; set; }
    
        public virtual tran_DebitorRec tran_DebitorRec { get; set; }
        public virtual tran_Creditor tran_Creditor { get; set; }
    }
}
