//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_JobDetail
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public int ProductID { get; set; }
        public decimal ProductPriceExactly { get; set; }
        public decimal JobQuantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual mas_Job mas_Job { get; set; }
        public virtual mas_Product mas_Product { get; set; }
    }
}
