//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_DebitorRec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tran_DebitorRec()
        {
            this.tran_DebitorRecDetail = new HashSet<tran_DebitorRecDetail>();
        }
    
        public int ID { get; set; }
        public string TransactionDebitorCode { get; set; }
        public int DebitorPeriodID { get; set; }
        public int DebitorID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public bool IsReceived { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsCancel { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsVat { get; set; }
        public decimal TranVat { get; set; }
        public decimal TranDiscount { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalAmountByBill { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int JobID { get; set; }
    
        public virtual mas_DebitorBillingPeriod mas_DebitorBillingPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_DebitorRecDetail> tran_DebitorRecDetail { get; set; }
        public virtual mas_Debtor mas_Debtor { get; set; }
    }
}
