//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_CreditorMill
    {
        public int ID { get; set; }
        public int TranCreditorID { get; set; }
        public int CreditorMillID { get; set; }
        public string CreditorMillCode { get; set; }
        public string CreditorMillName { get; set; }
        public bool IsVat { get; set; }
        public decimal VatInt { get; set; }
        public decimal VatAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remark { get; set; }
    
        public virtual mas_CreditorMill mas_CreditorMill { get; set; }
        public virtual tran_Creditor tran_Creditor { get; set; }
    }
}
