//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSBNPEntities : DbContext
    {
        public CSBNPEntities()
            : base("name=CSBNPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<key_DebitorBilling> key_DebitorBilling { get; set; }
        public virtual DbSet<mas_DebitorBillingPeriod> mas_DebitorBillingPeriod { get; set; }
        public virtual DbSet<mas_Product> mas_Product { get; set; }
        public virtual DbSet<sec_EmployeeUser> sec_EmployeeUser { get; set; }
        public virtual DbSet<tran_BillingPeriod> tran_BillingPeriod { get; set; }
        public virtual DbSet<tran_DebitorRec> tran_DebitorRec { get; set; }
        public virtual DbSet<tran_DebitorRecDetail> tran_DebitorRecDetail { get; set; }
        public virtual DbSet<vwrpt_SumTransactionCreditor> vwrpt_SumTransactionCreditor { get; set; }
        public virtual DbSet<vwrpt_TransactionCreditor> vwrpt_TransactionCreditor { get; set; }
        public virtual DbSet<vwrpt_TransactionDebitor_new> vwrpt_TransactionDebitor_new { get; set; }
        public virtual DbSet<tran_Creditor> tran_Creditor { get; set; }
        public virtual DbSet<vwrpt_VersusBuySell> vwrpt_VersusBuySell { get; set; }
        public virtual DbSet<log_History> log_History { get; set; }
        public virtual DbSet<mas_Job> mas_Job { get; set; }
        public virtual DbSet<mas_JobCreditor> mas_JobCreditor { get; set; }
        public virtual DbSet<mas_JobDetail> mas_JobDetail { get; set; }
        public virtual DbSet<mas_Debtor> mas_Debtor { get; set; }
        public virtual DbSet<vwrpt_VersusBuySellFromJob> vwrpt_VersusBuySellFromJob { get; set; }
        public virtual DbSet<mas_Creditor> mas_Creditor { get; set; }
        public virtual DbSet<mas_CreditorMill> mas_CreditorMill { get; set; }
        public virtual DbSet<tran_CreditorMill> tran_CreditorMill { get; set; }
        public virtual DbSet<tran_CreditorPrePaid> tran_CreditorPrePaid { get; set; }
        public virtual DbSet<tran_CreditorMillPrePaid> tran_CreditorMillPrePaid { get; set; }
        public virtual DbSet<vwrpt_TranCreditorMill> vwrpt_TranCreditorMill { get; set; }
    }
}
