//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_Debtor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_Debtor()
        {
            this.mas_Job = new HashSet<mas_Job>();
            this.tran_DebitorRec = new HashSet<tran_DebitorRec>();
        }
    
        public int ID { get; set; }
        public string DebtorCode { get; set; }
        public string DebtorName { get; set; }
        public string DebtorAddress { get; set; }
        public string DebtorTel { get; set; }
        public string DebtorContact { get; set; }
        public string DebtorTaxID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_Job> mas_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_DebitorRec> tran_DebitorRec { get; set; }
    }
}
