//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_Job()
        {
            this.mas_JobCreditor = new HashSet<mas_JobCreditor>();
            this.mas_JobDetail = new HashSet<mas_JobDetail>();
            this.tran_Creditor = new HashSet<tran_Creditor>();
            this.tran_CreditorPrePaid = new HashSet<tran_CreditorPrePaid>();
            this.tran_CreditorMillPrePaid = new HashSet<tran_CreditorMillPrePaid>();
        }
    
        public int ID { get; set; }
        public string JobCode { get; set; }
        public System.DateTime JobDateStart { get; set; }
        public string JobName { get; set; }
        public int DebtorID { get; set; }
        public decimal Budget { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsApprove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_JobCreditor> mas_JobCreditor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_JobDetail> mas_JobDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_Creditor> tran_Creditor { get; set; }
        public virtual mas_Debtor mas_Debtor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorPrePaid> tran_CreditorPrePaid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorMillPrePaid> tran_CreditorMillPrePaid { get; set; }
    }
}
