//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_CreditorMill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_CreditorMill()
        {
            this.tran_CreditorMill = new HashSet<tran_CreditorMill>();
            this.tran_CreditorMillPrePaid = new HashSet<tran_CreditorMillPrePaid>();
        }
    
        public int ID { get; set; }
        public string CreditorMillCode { get; set; }
        public string CreditorMillName { get; set; }
        public string CreditorMillAddress { get; set; }
        public string CreditorMillTel { get; set; }
        public string CreditorMillContact { get; set; }
        public string CreditorMillTaxID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorMill> tran_CreditorMill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran_CreditorMillPrePaid> tran_CreditorMillPrePaid { get; set; }
    }
}
