//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.BNP.App.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_CreditorPrePaid
    {
        public int ID { get; set; }
        public int BillingPeriodID { get; set; }
        public int CreditorID { get; set; }
        public int JobID { get; set; }
        public decimal TotalAmount { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual mas_Creditor mas_Creditor { get; set; }
        public virtual mas_Job mas_Job { get; set; }
        public virtual tran_BillingPeriod tran_BillingPeriod { get; set; }
    }
}
